LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := DDPlus
LOCAL_MODULE_STEM := DDPlus.apk
LOCAL_SRC_FILES := DDPlus.apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app/DDPlus
LOCAL_OVERRIDES_PACKAGES := MusicFx

include $(BUILD_PREBUILT)
